import StyleDictionary from "style-dictionary";

/**
 * Multi-brand token build. For each brand we compose base + semantic + that brand's
 * token file and emit:
 *  - dist/theme.css            (default brand only): :root CSS variables with references
 *    preserved, so semantic vars resolve through --brand-* at runtime.
 *  - dist/brand.<name>.css     : ONLY the brand-* variables, scoped to [data-brand="<name>"].
 *    Because theme.css keeps references, overriding --brand-* under a [data-brand] scope
 *    re-themes every semantic variable with zero component changes.
 *  - dist/tailwind.css         (default brand only): Tailwind v4 @theme mapping utilities
 *    to the runtime CSS variables.
 *  - src/tokens.generated.ts / src/tokens.<name>.generated.ts : typed resolved token maps
 *    (consumed by the restyle themes + direct reads).
 *
 * Brands are themes, never forks: a rebrand is a change to tokens/brand.<name>.json only.
 */

const BRANDS = ["aureva", "handal"];
const DEFAULT_BRAND = "aureva";

/** A color token is any token under `color.*` or `brand.color.*`. */
const isColorToken = (t) =>
  t.path[0] === "color" || (t.path[0] === "brand" && t.path[1] === "color");

/**
 * Format: a Tailwind v4 @theme block. Maps each color token to a `--color-<name>`
 * utility that references the runtime CSS variable, so Tailwind color utilities resolve
 * through the same variables a brand scope overrides. `t.name` is the kebab path
 * (e.g. `brand-color-primary`); the matching CSS variable is `--<name>`.
 */
StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.filter(isColorToken).map((t) => {
      // Drop a redundant leading `color-` so the Tailwind utility reads naturally
      // (e.g. `color-surface-canvas` → `bg-surface-canvas`;
      //  `brand-color-primary` → `--color-brand-primary` → `bg-brand-primary`).
      const utility = t.name.replace(/^color-/, "").replace(/^brand-color-/, "brand-");
      return `  --color-${utility}: var(--${t.name});`;
    });
    return `@import "tailwindcss";\n\n@theme inline {\n${lines.join("\n")}\n}\n`;
  },
});

/** Format: a typed TS module exporting the resolved token values, keyed by kebab name. */
StyleDictionary.registerFormat({
  name: "typescript/tokens-module",
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map(
      (t) => `  ${JSON.stringify(t.name)}: ${JSON.stringify(t.value ?? t.$value)},`,
    );
    return (
      "// AUTO-GENERATED by Style Dictionary. Do not edit by hand.\n" +
      "export const tokens = {\n" +
      entries.join("\n") +
      "\n} as const;\n\n" +
      "export type TokenName = keyof typeof tokens;\n"
    );
  },
});

/** Format: only brand.* variables, scoped to the brand's [data-brand] selector. */
StyleDictionary.registerFormat({
  name: "css/brand-scope",
  format: ({ dictionary, options }) => {
    const lines = dictionary.allTokens
      .filter((t) => t.path[0] === "brand")
      .map((t) => `  --${t.name}: ${t.value ?? t.$value};`);
    return `[data-brand="${options.brand}"] {\n${lines.join("\n")}\n}\n`;
  },
});

for (const brand of BRANDS) {
  const isDefault = brand === DEFAULT_BRAND;
  const sd = new StyleDictionary({
    source: ["tokens/base.json", "tokens/semantic.json", `tokens/brand.${brand}.json`],
    platforms: {
      ...(isDefault && {
        cssVariables: {
          transformGroup: "css",
          buildPath: "dist/",
          files: [
            {
              destination: "theme.css",
              format: "css/variables",
              options: { outputReferences: true },
            },
          ],
        },
        tailwind: {
          transformGroup: "css",
          buildPath: "dist/",
          files: [{ destination: "tailwind.css", format: "css/tailwind-theme" }],
        },
      }),
      brandCss: {
        transformGroup: "css",
        buildPath: "dist/",
        files: [
          {
            destination: `brand.${brand}.css`,
            format: "css/brand-scope",
            options: { brand },
          },
        ],
      },
      ts: {
        // Reuse the css group so token names are kebab-case (matching the CSS variables).
        transformGroup: "css",
        buildPath: "src/",
        files: [
          {
            destination: isDefault ? "tokens.generated.ts" : `tokens.${brand}.generated.ts`,
            format: "typescript/tokens-module",
            options: { outputReferences: false },
          },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}
