import StyleDictionary from "style-dictionary";

/**
 * Build the neutral DTCG token source into platform outputs:
 *  - dist/theme.css        : :root CSS variables (web runtime-theming contract)
 *  - dist/tailwind.css      : Tailwind v4 @theme layer mapping utilities to those vars
 *  - src/tokens.generated.ts: typed token object (consumed by the restyle theme + direct reads)
 *
 * Brand tokens (brand.*) are emitted as CSS variables so the settings GUI can override them
 * at runtime under a [data-brand] scope without a rebuild.
 */

/** A color token is any token under `color.*` or `brand.color.*`. */
const isColorToken = (t) =>
  t.path[0] === "color" || (t.path[0] === "brand" && t.path[1] === "color");

/**
 * Format: a Tailwind v4 @theme block. Maps each color token to a `--color-<name>`
 * utility that references the runtime CSS variable, so Tailwind color utilities resolve
 * through the same variables the settings GUI overrides. `t.name` is the kebab path
 * (e.g. `brand-color-primary`); the matching CSS variable is `--<name>`.
 */
StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.filter(isColorToken).map((t) => {
      // Drop a redundant leading `color-` so the Tailwind utility reads naturally
      // (e.g. `color-neutral-50` → `--color-neutral-50` → `bg-neutral-50`;
      //  `brand-color-primary` → `--color-brand-primary` → `bg-brand-primary`).
      const utility = t.name.replace(/^color-/, "").replace(/^brand-color-/, "brand-");
      return `  --color-${utility}: var(--${t.name});`;
    });
    return `@import "tailwindcss";\n\n@theme inline {\n${lines.join("\n")}\n}\n`;
  },
});

/** Format: a typed TS module exporting the resolved token values, keyed by kebab name. */
StyleDictionary.registerFormat({
  name: "typescript/tokens-module",
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map(
      (t) => `  ${JSON.stringify(t.name)}: ${JSON.stringify(t.value ?? t.$value)},`,
    );
    return (
      "// AUTO-GENERATED by Style Dictionary. Do not edit by hand.\n" +
      "export const tokens = {\n" +
      entries.join("\n") +
      "\n} as const;\n\n" +
      "export type TokenName = keyof typeof tokens;\n"
    );
  },
});

export default {
  source: ["tokens/**/*.json"],
  platforms: {
    cssVariables: {
      transformGroup: "css",
      buildPath: "dist/",
      files: [
        {
          destination: "theme.css",
          format: "css/variables",
          options: { outputReferences: true },
        },
      ],
    },
    tailwind: {
      transformGroup: "css",
      buildPath: "dist/",
      files: [{ destination: "tailwind.css", format: "css/tailwind-theme" }],
    },
    ts: {
      // Reuse the css group so token names are kebab-case (matching the CSS variables).
      transformGroup: "css",
      buildPath: "src/",
      files: [
        {
          destination: "tokens.generated.ts",
          format: "typescript/tokens-module",
          options: { outputReferences: false },
        },
      ],
    },
  },
};
